PROJECT/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView
from organization.views import DashboardView
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(DashboardView.as_view()), name='dashboard'),
	path('order/', include(('order.urls', 'order'), namespace='order')),
	path('route/', include(('route.urls', 'route'), namespace='route')),
	path('driver/', include(('driver.urls', 'driver'), namespace='driver')),
	path('vehicle/', include(('vehicle.urls', 'order'), namespace='vehicle')),
	path('accounts/', include(('user.urls', 'accounts'), namespace='accounts')),
	path('organizations/', include(('organization.urls', 'organization'), namespace='organization')),

    path('api/v1/', include('api.urls')),
    #path('', RedirectView.as_view(url=reverse_lazy('organizations:index')), name='home'),
]

api/order/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
	path('', views.FilterView.as_view()),
    path('by-ref', views.RefView.as_view()),
	path('sync', views.SyncOrderView.as_view()),
	path('replicate', views.ReplicateOrderView.as_view()),

	path('create', views.CreateView.as_view()),
    path('<int:pk>', views.IndexView.as_view()),
    path('<int:pk>/cancel', views.CancelView.as_view()),
]

api/urls.py
from django.urls import path, include

urlpatterns = [
    path("user/", include("api.user.urls")),
    path("order/", include("api.order.urls")),
    # Uses custom token
    path("driver/", include("api.driver.urls")),
    path("appointments/", include("api.appointments.urls")),
    # path("organizations/", include("api.organizations.urls")),
]

order/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

urlpatterns = [
    path('track/<str:public_id>', views.ReviewView.as_view(), name='track'),
    path('review/<str:public_id>', views.ReviewView.as_view(), name='review'),

    path('', login_required(views.IndexView.as_view()), name='index'),
    path('map', login_required(views.MapView.as_view()), name='map'),
    path('plan', login_required(views.PlanView.as_view()), name='plan'),
    path('json', login_required(views.OrdersJsonView.as_view()), name='json'),
    path('create', login_required(views.CreateView.as_view()), name='create'),
    path('<int:pk>', login_required(views.OrderView.as_view()), name='detail'),
    path('reviews', login_required(views.ReviewsView.as_view()), name='reviews'),
    path('export', login_required(views.ExportOrdersView.as_view()), name='export'),
    path('payments', login_required(views.PaymentsView.as_view()), name='payments'),
    path('track', login_required(views.OrderTrackingIframeView.as_view()), name='track'),
    path('route/json', login_required(views.RouteJsonView.as_view()), name='route-json'),
    path('<int:pk>/partial', login_required(views.OrderPartialView.as_view()), name='detail-partial'),
    path('export/reviews', login_required(views.ExportReviewsView.as_view()), name='export-reviews'),
    path('upload/iframe', login_required(views.UploadOrdersIframeView.as_view()), name='upload-iframe'),
    path('state/<int:pk>/iframe', login_required(views.StateIframeView.as_view()), name='state-iframe'),
    path('assign/<int:pk>/iframe', login_required(views.AssignIframeView.as_view()), name='assign-iframe'),
    path('pickup/<int:pk>/iframe', login_required(views.PickupIframeView.as_view()), name='pickup-iframe'),
    path('dropoff/<int:pk>/iframe', login_required(views.DropoffIframeView.as_view()), name='dropoff-iframe'),
    path('multi-assign/iframe', login_required(views.MultiAssignIframeView.as_view()), name='multi-assign-iframe'),
    path('ajax-assign/iframe', login_required(views.AjaxAssignIframeView.as_view()), name='ajax-assign-iframe'),
    path('export/driver/reviews', login_required(views.ExportDriverReviewsView.as_view()), name='export-driver-reviews'),
    path('ajax-assign/iframe/<int:vehicle_id>/<int:route_id>', login_required(views.AjaxAssignIframeView.as_view()), name='ajax-assign-iframe'),
]

order/models.py
from django.contrib.postgres.fields import ArrayField
from django.db.models.signals import post_save
from django.db import connection, OperationalError
from organization.models import Organization
from django.dispatch import receiver
from django.utils import timezone
from driver.models import Driver, Coords
from user.models import User
from django.db import models
import datetime, validators

from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer




# from django_fsm import FSMIntegerField

# For logging
class OrderStatusLog(models.Model):
	order_id = models.ForeignKey('Order', on_delete=models.CASCADE, related_name='order_status_logs')
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now_add=True)
	action = models.CharField(max_length=50)

	class Meta:
		"""Meta definition for OrderStatusLog."""

		verbose_name = 'OrderStatusLog'
		verbose_name_plural = 'OrderStatusLogs'

	def __str__(self):
		"""Unicode representation of OrderStatusLog."""
		return f'{self.action}'


class OrderItem(models.Model):
	COLLECTED = 1
	NOT_COLLECTED = 2
	DAMAGED = 3
	REJECTED = 4
	FAILED = 5
	DELIVERED = 6
	RETURNED = 7

	STATUSES = (
		(NOT_COLLECTED,'Not collected'),
		(COLLECTED,'Collected for delivery'),
		(DAMAGED,'Damaged in transit'),
		(REJECTED,'Rejected by recipeint'),
		(FAILED,'Failed'),
		(DELIVERED,'Delivered'),
		(RETURNED, 'Returned to warehouse'),
	)
	name = models.CharField(max_length=75)
	paid = models.BooleanField(default=False)
	state = models.PositiveIntegerField(choices=STATUSES,default=NOT_COLLECTED)
	price = models.DecimalField(max_digits=50,decimal_places=2, null=True)
	width = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	weight = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	length = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	height = models.DecimalField(max_digits=12, decimal_places=2, null=True)

class OrderFailure(models.Model):
	reason = models.CharField(max_length=1024)
	created = models.DateTimeField(auto_now_add=True)

class Order(models.Model):
	#payment status
	PREPAID = 1
	POSTPAID = 2
	POSTPAID_MM = 3
	CREDIT = 4

	#Vehicle types

	TBD = 0
	MOTOBIKE = 1
	MOTOBIKEWITHBOX = 2
	PICKUP_OPEN = 3
	PICKUP_CLOSED = 4
	VAN = 5
	TRUCK_3T = 6
	TRUCK_4T = 7
	TRUCK_5T = 8
	TRUCK_7T = 9
	TRUCK_10T = 10
	TRUCK_12T = 11
	TRUCK_25T = 12
	TRUCK_27T = 13
	TRUCK_3T_REFER = 14
	TRAILER = 15
	INTER_COUNTY = 16
	GLOBAL = 17


	PAYMENT_METHOD = (
		(PREPAID,'Prepaid'),
		(POSTPAID,'Postpaid - Cash'),
		(POSTPAID_MM,'Postpaid - Mobile money'),
		(CREDIT,'Credit'),
	)

	VEHICLE_TYPES = (
		(TBD, 'TBD'),
		(MOTOBIKE, 'Motorbike'),
		(MOTOBIKEWITHBOX, 'Motorbike with box'),
		(PICKUP_OPEN, 'Pick Up Open'),
		(PICKUP_CLOSED, 'Pick Up Closed'),
		(VAN, 'Van'),
		(TRUCK_3T, 'Truck 3 Tone'),
		(TRUCK_4T, 'Truck 4 Tone'),
		(TRUCK_5T, 'Truck 5 Tone'),
		(TRUCK_7T, 'Truck 7 Tone'),
		(TRUCK_10T, 'Truck 10 Tone'),
		(TRUCK_12T, 'Truck 12 Tone'),
		(TRUCK_25T, 'Truck 25 Tone'),
		(TRUCK_27T, 'Truck 27 Tone'),
		(TRUCK_3T_REFER, 'Truck 3 Tone Refer'),
		(TRAILER, 'Trailer 27 Ton with container'),
		(INTER_COUNTY, 'Inter-county'),
		(GLOBAL, 'Global'),
	)


	# delivery state
	DRAFT = 1
	""" submitted time """
	SUBMITTED_PENDING_VENDOR_PICK_UP = 2
	SUBMITTED_PENDING_FOWARD_DELIVERY = 3
	""" Dispatched """
	DISPATCHED = 4
	""" Arrival at client """
	ARRAVAL_AT_CLIENT = 5
	""" Failed """
	FAILED_AT_CLIENT = 6
	""" delivered """
	DELIVERED = 7
	""" submit to warehouse """
	SUBMITTED_RETURN_TO_WAREHOUSE = 8
	""" complete """
	COMPLETED_TO_WAREHOUSE = 9
	""" vendor """
	SUBMITTED_RETURN_TO_VENDOR = 10
	""" complete to vendor  """
	COMPLETED_TO_VENDOR = 11
	""" Admin approve all completed orders """
	CANCELLED = 12
	""" Admin approve all completed orders """
	RESCHEDULED = 13
	""" Order has been rescheduled """

	DELIVERY_STATE = (
		(DRAFT,'Submitted'),
		(SUBMITTED_PENDING_VENDOR_PICK_UP,'Driver Unassigned'),
		(SUBMITTED_PENDING_FOWARD_DELIVERY,'Driver Assigned'),
		(DISPATCHED,'in progress'),
		(ARRAVAL_AT_CLIENT, 'Arrival at client'),
		(FAILED_AT_CLIENT, 'Failed'),
		(DELIVERED, 'Delivered'),
		(SUBMITTED_RETURN_TO_WAREHOUSE, 'failed awaiting warehouse'),
		(COMPLETED_TO_WAREHOUSE, 'Delivered at warehouse'),
		(SUBMITTED_RETURN_TO_VENDOR, 'Returned from warehouse'),
		(COMPLETED_TO_VENDOR, 'Recieved from warehouse'),
		(CANCELLED, 'Cancelled'),
		(RESCHEDULED, 'Rescheduled'),

	)

	ANYTIME = 1
	MORNING = 2
	AFTERNOON = 3

	PREFERED_TIME = (
		(ANYTIME, 'Anytime'),
		(MORNING, 'Morning'),
		(AFTERNOON, 'Afternoon')
	)
	paid = models.BooleanField(default=False)
	notes = models.TextField(blank=True, null=True)
	ref = models.CharField(max_length=50, null=True)
	sid = models.CharField(max_length=50, null=True, blank=True)
	public_id = models.CharField(max_length=75, null=True, unique=True)
	state = models.PositiveIntegerField(choices=DELIVERY_STATE,default=DRAFT)
	# Bump state to status
	# status = FSMIntegerField(default=DRAFT)
	payment_method = models.PositiveSmallIntegerField(choices=PAYMENT_METHOD,default=PREPAID)


	modified = models.DateTimeField(auto_now=True)
	created = models.DateTimeField(auto_now_add=True)


	datetime_failed = models.DateTimeField(null=True)
	datetime_started = models.DateTimeField(null=True)
	datetime_arrived = models.DateTimeField(null=True)
	datetime_assigned = models.DateTimeField(null=True)
	datetime_accepted = models.DateTimeField(null=True)
	datetime_reviewed = models.DateTimeField(null=True)
	datetime_completed = models.DateTimeField(null=True)
	datetime_ordered = models.DateTimeField(default=timezone.now)

	failure_reason = models.CharField(max_length=255, null=True)
	complete_lat = models.DecimalField(max_digits=22, decimal_places=16, null=True)
	complete_lng = models.DecimalField(max_digits=22, decimal_places=16, null=True)

	payment_notes = models.CharField(max_length=2048, null=True)
	signature = models.URLField(max_length=2048, null=True)
	pod_images = ArrayField(models.URLField(max_length=2048), null=True)

	price = models.DecimalField(max_digits=50,decimal_places=2, null=True)
	width = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	weight = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	length = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	height = models.DecimalField(max_digits=12, decimal_places=2, null=True)

	pickup_location_details = models.TextField(null=True)
	pickup_location_name = models.CharField(max_length=255)
	pickup_contact_phone_number = models.BigIntegerField(null=True)
	pickup_contact_name = models.CharField(max_length=255, null=True)
	pickup_contact_email = models.EmailField(max_length=254, null=True)
	pickup_location_name_more = models.CharField(max_length=255, null=True)
	pickup_lat = models.DecimalField(max_digits=22, decimal_places=16, null=True)
	pickup_lng = models.DecimalField(max_digits=22, decimal_places=16, null=True)

	dropoff_location_details = models.TextField(null=True)
	dropoff_location_name = models.CharField(max_length=255)
	dropoff_contact_phone_number = models.BigIntegerField(null=True)
	dropoff_contact_name = models.CharField(max_length=255, null=True)
	dropoff_contact_email = models.EmailField(max_length=254, null=True)
	dropoff_location_name_more = models.CharField(max_length=255, null=True)
	dropoff_lat = models.DecimalField(max_digits=22, decimal_places=16, null=True)
	dropoff_lng = models.DecimalField(max_digits=22, decimal_places=16, null=True)

	customer_phone_number = models.BigIntegerField(null=True)
	customer_email = models.EmailField(max_length=254, null=True)
	customer_last_name = models.CharField(max_length=75, null=True)
	customer_first_name = models.CharField(max_length=75, null=True)

	review = models.CharField(max_length=2048, null=True, blank=True)
	rating = models.DecimalField(max_digits=2, decimal_places=1, null=True)

	rider = models.ForeignKey(Driver, on_delete=models.SET_NULL, null=True)
	vehicle_type = models.PositiveSmallIntegerField(choices=VEHICLE_TYPES, default=TBD)

	preffered_delivery_date = models.DateField(default=datetime.date.today)
	preffered_delivery_period = models.PositiveSmallIntegerField(default=ANYTIME, choices=PREFERED_TIME)

	failures = models.ManyToManyField(OrderFailure)
	organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
	added_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name="order_added_by")
	modified_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name="order_modified_by")

	items = models.ManyToManyField(OrderItem)

	prev_id = models.BigIntegerField(null=True, db_index=True)
	prev_id_external = models.BigIntegerField(null=True, db_index=True)

	class Meta:
		unique_together = [['ref', 'organization']]
		index_together = [
			["rider", "datetime_ordered", "state", "organization"],
			["datetime_ordered", "state", "organization"],
			["rating", "datetime_ordered", "organization"],
		]

	def mpesa_code(self):


			# check if mpesa transaction exists
		mpesa_exists = MpesaPayments.objects.filter(order__pk =self.pk).exists()

		if mpesa_exists:
			details = MpesaPayments.objects.filter(order__pk =self.pk)
			return details
		else:
			return None

	def driver_location(self):
		if self.rider is not None and self.rider.get_driver_location() is not None:
			return self.rider.get_driver_location()

		if validators.truthy(self.pickup_lat) and \
			validators.truthy(self.pickup_lng) and \
			validators.between(self.pickup_lng, -180.0, 180.0) and \
			validators.between(self.pickup_lat, -90.0, 90.0):
			c = Coords()
			c.lat = self.pickup_lat
			c.lng = self.pickup_lng
			return c

		return None


	def time_ago(self):
		d = timezone.now() - self.created
		return self.hms(d.total_seconds())

	def driver_time_ago(self):
		if self.datetime_assigned:
			d = timezone.now() - self.datetime_assigned
			return self.hms(d.total_seconds())
		else:

templates/order/partials/detail.html
						<li class="do-blink" id="order-{{ object.pk }}">
							<!-- Job Listing -->
							<div class="job-listing">

								<!-- Job Listing Details -->
								<div class="job-listing-details">
									<!-- Details -->
									<div class="job-listing-description">
										<h3 class="job-listing-title">
											<div class="checkbox checkbox1">
												<input type="checkbox" id="checkbox-{{ object.pk }}" class="checkbox2" value="{{ object.pk }}">
												<label for="checkbox-{{ object.pk }}"><span class="checkbox-icon"></span> </label>										
											</div>
											<a href="{% url 'order:detail' object.pk %}">{{object.pickup_location_name }} &raquo;&raquo;&raquo; {{object.dropoff_location_name }}</a>
										</h3>
										{% if object.state == 7 %}
											<span class="capitalize dashboard-status-button blue">{{object.get_state_display|lower}}</span>
										{% elif object.state == 4 or  object.state == 5 %}
											<a data-href="{% url 'order:state-iframe' object.pk %}" class="do-change-state" href="#"><span class="capitalize dashboard-status-button green">{{object.get_state_display|lower}}&nbsp;<i class="icon-feather-edit"></i></span></a>

										{% elif object.state == 12 or object.state < 3 %}
											<a data-href="{% url 'order:state-iframe' object.pk %}" class="do-change-state" href="#"><span class="capitalize dashboard-status-button red">{{object.get_state_display|lower}}&nbsp;<i class="icon-feather-edit"></i></span></a>
										{% elif object.state == 6  %}
											<span class="capitalize dashboard-status-button red">{{object.get_state_display|lower}}</span>{% if object.failure_reason %}&nbsp;<mark class="color">“{{object.failure_reason}}”</mark>{% endif %}
										{% else %}
											<a  data-href="{% url 'order:state-iframe' object.pk %}" class="do-change-state" href="#"><span class="capitalize dashboard-status-button yellow">{{object.get_state_display|lower}}&nbsp;<i class="icon-feather-edit"></i></span></a>
										{% endif %}


										<!-- Job Listing Footer -->
										<div class="job-listing-footer">
											<ul>
												<li><i class="icon-material-outline-business-center"></i> ID: <strong>#{{object.id}}</strong></li>
												{% if object.ref %}
												<li><i class="icon-material-outline-business-center"></i> Ref: <strong>{{object.ref}}</strong></li>
												{% endif %}
												<li><i class="icon-material-outline-access-time"></i>{{ object.time_ago }}</li>
											</ul>
											{% if object.rider %}
											<ul>
												<li><i class="icon-line-awesome-motorcycle"></i> <span class="capitalize">{{ object.rider.full_names | lower}}</span></li>
												<li><i class="icon-feather-phone"></i> <a href="tel:+{{object.rider.phone_number}}">+{{object.rider.phone_number}}</a></li>

											</ul>
											{% endif %}
											<ul>

												{% if object.datetime_ordered %}
													<li><i class="icon-material-outline-date-range"></i> Ordered: {{object.datetime_ordered|date:'d M, Y H:i' }}</li>
												{% endif %}
												{% if object.created %}
													<li><i class="icon-material-outline-date-range"></i> Submited: {{object.created|date:'d M, Y H:i' }}</li>
												{% endif %}

												{% if object.datetime_assigned %}
													<li><i class="icon-material-outline-date-range"></i> Driver assigned:  {{object.datetime_assigned|date:'d M, Y H:i' }}</li>
												{% endif %}

												{% if object.datetime_accepted %}
													<li><i class="icon-material-outline-date-range"></i> Driver accepted: {{object.datetime_accepted|date:'d M, Y H:i' }}</li>
												{% endif %}
												{% if object.datetime_started %}
													<li><i class="icon-material-outline-date-range"></i> Driver started: {{object.datetime_started|date:'d M, Y H:i' }}</li>
												{% endif %}
												{% if object.datetime_arrived %}
													<li><i class="icon-material-outline-date-range"></i> Driver arrived: {{object.datetime_arrived|date:'d M, Y H:i' }}</li>
												{% endif %}
												{% if object.datetime_reviewed %}
													<li><i class="icon-material-outline-date-range"></i> Customer reviewed: {{object.datetime_reviewed|date:'d M, Y H:i' }}</li>
												{% endif %}

												{% if object.datetime_failed %}
													<li><i class="icon-material-outline-date-range"></i> Datetime failed: {{object.datetime_failed|date:'d M, Y H:i' }}</li>
												{% endif %}
												{% if object.datetime_completed %}
													<li><i class="icon-material-outline-date-range"></i> Completed: {{object.datetime_completed|date:'d M, Y H:i' }}</li>
												{% endif %}
											</ul>

										</div>
									</div>
								</div>
							</div>





							<!-- Buttons -->
							<div class="buttons-to-right always-visible">
								{% if object.state < 7 %}
									{% if object.rider %}
									<a href="#" data-href="{% url 'order:assign-iframe' object.pk %}" class="button gray ripple-effect do-assign"><i class="icon-line-awesome-motorcycle"></i> Driver &nbsp;&nbsp;<i class="icon-feather-check-circle"></i></a>
									{% else %}
									<a href="#" data-href="{% url 'order:assign-iframe' object.pk %}" class="button dark ripple-effect do-assign"><i class="icon-line-awesome-motorcycle"></i> Driver &nbsp;&nbsp;<i class="icon-feather-minus-circle"></i></a>
									{% endif %}
								{% endif %}

								<a href="#" data-href="{% url 'order:pickup-iframe' object.pk %}" class="button gray ripple-effect do-assign"><i class="icon-material-outline-location-on"></i> Pick-up </a>

								<a href="#" data-href="{% url 'order:dropoff-iframe' object.pk %}" class="button gray ripple-effect do-assign"><i class="icon-material-outline-location-on"></i> Drop-off </a>


<!--
								{% if object.state == 7 %}
								<a href="#" class="button gray ripple-effect ico" data-tippy-placement="top" data-tippy="" data-original-title="Edit"><i class="icon-feather-eye"></i></a>
								{% else %}
								<a href="#" class="button gray ripple-effect ico" data-tippy-placement="top" data-tippy="" data-original-title="Edit"><i class="icon-feather-edit"></i></a>
								{% endif %}
-->
							</div>

							{% if object.rating %}

							<div class="boxed-list-item">
								<!-- Content -->
								<div class="item-content">
									<h4>Rating</h4>
									<div class="item-details margin-top-10">
										<div class="star-rating" data-rating="{{ object.rating }}"></div>
										<div class="detail-item"><i class="icon-material-outline-date-range"></i> {{object.datetime_reviewed|date:'d M, Y H:i' }}</div>
									</div>
									{% if object.review %}
									<div class="item-description">
										<p><i class="icon-material-outline-rate-review"></i>&nbsp; {{ object.review }}</p>
									</div>
									{% endif %}
								</div>
							</div>
							{% endif %}
						</li>

templates/order/partials/drop_off.html
<a href="#order-drop-off-{{ object.pk }}" class="popup-with-zoom-anim button gray ripple-effect"><i class="icon-material-outline-location-on"></i> Drop-off </a>
<div id="order-drop-off-{{ object.pk }}" class="zoom-anim-dialog mfp-hide dialog-with-tabs small-dialog-2">

	<!--Tabs -->
	<div class="sign-in-form">

		<ul class="popup-tabs-nav">
		</ul>

		<div class="popup-tabs-container">

			<!-- Tab -->
			<div class="popup-tab-content" id="tab2">
				
				<!-- Welcome Text -->
				<div class="welcome-text">
					<h3>Drop-off</h3>
				</div>

				<div class="job-listing-footer">
					<ul class="dashboard-box-list">
						<li><i class="icon-feather-user"></i>&nbsp;&nbsp;
							{% if object.dropoff_contact_name %}
								<h4 class="capitalize">{{object.dropoff_contact_name  | lower }}</h4>
							{% endif %}
						</li>
					</ul>
					<ul class="dashboard-box-list">
						<li><i class="icon-feather-phone"></i>&nbsp;&nbsp; 
							{% if object.dropoff_contact_phone_number %}
								<span class="capitalize"><a href="tel:+{{object.dropoff_contact_phone_number}}">+{{object.dropoff_contact_phone_number}}</a></span>
							{% endif %}
						</li>
					</ul>
					<ul class="dashboard-box-list">
						<li><i class="icon-material-outline-location-on"></i>&nbsp;&nbsp; {{object.dropoff_location_name}}</li>
					</ul>

				</div>

			</div>

		</div>
	</div>
</div>
<!-- Leave a Review Popup / End -->

templates/order/partials/pick_up.html
<a href="#order-pick-up-{{ object.pk }}" class="popup-with-zoom-anim button gray ripple-effect"><i class="icon-material-outline-location-on"></i> Pick-up </a>
<div id="order-pick-up-{{ object.pk }}" class="zoom-anim-dialog mfp-hide dialog-with-tabs small-dialog-2">

	<!--Tabs -->
	<div class="sign-in-form">

		<ul class="popup-tabs-nav">
		</ul>

		<div class="popup-tabs-container">

			<!-- Tab -->
			<div class="popup-tab-content" id="tab2">
				
				<!-- Welcome Text -->
				<div class="welcome-text">
					<h3>Pick-up</h3>
				</div>


					
				<div class="job-listing-footer">
					<ul class="dashboard-box-list">
						<li><i class="icon-feather-user"></i>&nbsp;&nbsp;
							{% if object.pickup_contact_name %}
								<h4 class="capitalize">{{object.pickup_contact_name  | lower }}</h4>
							{% endif %}
						</li>
					</ul>
					<ul class="dashboard-box-list">
						<li><i class="icon-feather-phone"></i>&nbsp;&nbsp; 
							{% if object.pickup_contact_phone_number %}
								<span class="capitalize"><a href="tel:+{{object.pickup_contact_phone_number}}">+{{object.pickup_contact_phone_number}}</a></span>
							{% endif %}
						</li>
					</ul>
					<ul class="dashboard-box-list">
						<li><i class="icon-material-outline-location-on"></i>&nbsp;&nbsp; {{object.pickup_location_name}}</li>
					</ul>

				</div>

			</div>

		</div>
	</div>
</div>
<!-- Leave a Review Popup / End -->

templates/order/partials/upload.html
<a href="#order-upload-dialog" class="popup-with-zoom-anim button ripple-effect"><i class="icon-feather-upload"></i> Upload orders </a>
<div id="order-upload-dialog" class="zoom-anim-dialog mfp-hide dialog-with-tabs small-dialog-2">

	<!--Tabs -->
	<div class="sign-in-form">

		<ul class="popup-tabs-nav">
		</ul>

		<div class="popup-tabs-container">

			<!-- Tab -->
			<div class="popup-tab-content" id="tab2">
				
				<!-- Welcome Text -->
				<div class="welcome-text">
					<h3>Upload from CSV</h3>
					<span>Not sure how to get started? <a href="#">Download sample</a></span>
				</div>
					
				<form action="" method="post" enctype="multipart/form-data">
					{% csrf_token %} {{object_list.upload_from}}
            		<input type="submit" value="Submit" class="button full-width button-sliding-icon ripple-effect">
				</form>

			</div>

		</div>
	</div>
</div>
<!-- Leave a Review Popup / End -->