PROJECT/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView
from organization.views import DashboardView
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(DashboardView.as_view()), name='dashboard'),
	path('order/', include(('order.urls', 'order'), namespace='order')),
	path('route/', include(('route.urls', 'route'), namespace='route')),
	path('driver/', include(('driver.urls', 'driver'), namespace='driver')),
	path('vehicle/', include(('vehicle.urls', 'order'), namespace='vehicle')),
	path('accounts/', include(('user.urls', 'accounts'), namespace='accounts')),
	path('organizations/', include(('organization.urls', 'organization'), namespace='organization')),

    path('api/v1/', include('api.urls')),
    #path('', RedirectView.as_view(url=reverse_lazy('organizations:index')), name='home'),
]

api/organizations/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views

urlpatterns = [
    path("drivers", views.AuthView.as_view()),
]

api/urls.py
from django.urls import path, include

urlpatterns = [
    path("user/", include("api.user.urls")),
    path("order/", include("api.order.urls")),
    # Uses custom token
    path("driver/", include("api.driver.urls")),
    path("appointments/", include("api.appointments.urls")),
    # path("organizations/", include("api.organizations.urls")),
]

order/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

urlpatterns = [
    path('track/<str:public_id>', views.ReviewView.as_view(), name='track'),
    path('review/<str:public_id>', views.ReviewView.as_view(), name='review'),

    path('', login_required(views.IndexView.as_view()), name='index'),
    path('map', login_required(views.MapView.as_view()), name='map'),
    path('plan', login_required(views.PlanView.as_view()), name='plan'),
    path('json', login_required(views.OrdersJsonView.as_view()), name='json'),
    path('create', login_required(views.CreateView.as_view()), name='create'),
    path('<int:pk>', login_required(views.OrderView.as_view()), name='detail'),
    path('reviews', login_required(views.ReviewsView.as_view()), name='reviews'),
    path('export', login_required(views.ExportOrdersView.as_view()), name='export'),
    path('payments', login_required(views.PaymentsView.as_view()), name='payments'),
    path('track', login_required(views.OrderTrackingIframeView.as_view()), name='track'),
    path('route/json', login_required(views.RouteJsonView.as_view()), name='route-json'),
    path('<int:pk>/partial', login_required(views.OrderPartialView.as_view()), name='detail-partial'),
    path('export/reviews', login_required(views.ExportReviewsView.as_view()), name='export-reviews'),
    path('upload/iframe', login_required(views.UploadOrdersIframeView.as_view()), name='upload-iframe'),
    path('state/<int:pk>/iframe', login_required(views.StateIframeView.as_view()), name='state-iframe'),
    path('assign/<int:pk>/iframe', login_required(views.AssignIframeView.as_view()), name='assign-iframe'),
    path('pickup/<int:pk>/iframe', login_required(views.PickupIframeView.as_view()), name='pickup-iframe'),
    path('dropoff/<int:pk>/iframe', login_required(views.DropoffIframeView.as_view()), name='dropoff-iframe'),
    path('multi-assign/iframe', login_required(views.MultiAssignIframeView.as_view()), name='multi-assign-iframe'),
    path('ajax-assign/iframe', login_required(views.AjaxAssignIframeView.as_view()), name='ajax-assign-iframe'),
    path('export/driver/reviews', login_required(views.ExportDriverReviewsView.as_view()), name='export-driver-reviews'),
    path('ajax-assign/iframe/<int:vehicle_id>/<int:route_id>', login_required(views.AjaxAssignIframeView.as_view()), name='ajax-assign-iframe'),
]

organization/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

urlpatterns = [
    path('<int:pk>',login_required(views.ItemView.as_view()), name='detail'),
    path('start', login_required(views.RedirectView.as_view()), name='index'),
    path('create', login_required(views.CreateView.as_view()), name='create'),
    path('join/<str:token>', views.OrganizationJoinView.as_view(), name='join'),
    path('add/user', login_required(views.OrganizationAddUserView.as_view()), name='add-user'),
    path('add/sms_gateway', login_required(views.OrganizationAddSmsGateway.as_view()), name='add_sms_gateway'),
    path('verify_sms_settings', login_required(views.VerifySmsSettings.as_view()), name='verify_sms_settings'),
    path('add/m_details', login_required(views.OrganizationAddMpesaDetails.as_view()), name='add-m-details'),
    path('switch/<int:organization_user_id>',login_required(views.SwitchView.as_view()), name='switch'),
    path('remove/user/<int:organization_user_id>',login_required(views.OrganizationRemoveUserIframeView.as_view()), name='remove-user'),
    path('stkpush_callback', views.STKPushCallback.as_view(), name='stkpush_callback'),
    path('kopokopo_callback', views.KopokopoCallback.as_view(), name='kopokopo_callback'),
]

api/organizations/models.py
from django.db import models

# Create your models here.

organization/models.py
from django.db import models
from user.models import User
from django.utils import timezone


class Organization(models.Model):
    name = models.CharField(max_length=75)
    country = models.CharField(max_length=255)
    timezone = models.CharField(max_length=75)
    is_active = models.BooleanField(default=True)
    modified = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    callback_url = models.URLField(max_length=2048, null=True)
    sync_callback_url = models.URLField(max_length=2048, null=True)
    googlemap_api_key = models.CharField(max_length=255, null=True)
    send_order_received_sms = models.BooleanField(default=True)
    send_driver_assign_sms = models.BooleanField(default=True)
    send_driver_reassign_sms = models.BooleanField(default=True)
    send_driver_start_sms = models.BooleanField(default=False)
    send_driver_complete_sms = models.BooleanField(default=True)
    allow_driver_to_self_assign_orders = models.BooleanField(default=False)

    order_received_sms = models.CharField(
        max_length=150, default="Hi {{first_name}}, your order #{{order_ref}} has be been received and will be dispatched shortly.")
    driver_assign_sms = models.CharField(
        max_length=150, default="A rider has been assigned to your order #{{order_ref}}. {{rider_name}} will contact you on  {{rider_phone}}")
    driver_reassign_sms = models.CharField(
        max_length=150, default="A different rider has been assigned to your order #{{order_ref}}. {{rider_name}} will contact you on  {{rider_phone}}")
    driver_start_sms = models.CharField(
        max_length=150, default="Your rider is on the way. {{rider_name}} will contact you on {{rider_phone}}")
    driver_complete_sms = models.CharField(
        max_length=150, default="Thank you. How was your experience. Leave us a rating.")

    def members(self):
        return OrganizationUser.objects.filter(organization=self, deleted=False)

    def mpesa_details(self):
        return OrganizationMpesaDetails.objects.get(organization=self)


class OrganizationUser(models.Model):
    deleted = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    modified = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['user', 'organization']


class OrganizationInvite(models.Model):
    name = models.CharField(max_length=75)
    email = models.EmailField(max_length=255)
    deleted = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    modified = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    token = models.CharField(max_length=48, unique=True, null=True)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['email', 'organization']


class OrganizationSmsProvider(models.Model):
    AFRICASTALKING = 1
    INFOBIP = 2
    VONAGE = 3
    TWILIO = 4
    VASPRO = 5
    PROVIDERS = [
        (AFRICASTALKING, 'Africa\'s talking'),
        (INFOBIP, 'Infobip'),
        (VONAGE, 'Vonage'),
        (TWILIO, 'Twilio'),
        (VASPRO, 'Vaspro'),
    ]

    organization = models.OneToOneField(Organization, on_delete=models.CASCADE)
    provider = models.PositiveSmallIntegerField(
        choices=PROVIDERS, default=None)
    sender_id = models.CharField(max_length=150)
    api_key = models.CharField(max_length=200, null=True, blank=True)
    username = models.CharField(max_length=150, null=True, blank=True)
    base_url = models.URLField(null=True, blank=True)
    api_secret = models.CharField(max_length=200, null=True, blank=True)
    account_sid = models.CharField(max_length=200, null=True, blank=True)
    auth_token = models.CharField(max_length=200, null=True, blank=True)
    verification_code = models.CharField(max_length=6, null=True, blank=True)
    verified = models.BooleanField(default=False)


class OrganizationMpesaDetails(models.Model):
    DARAJA = 1
    KOPOKOPO = 2
    IMPLEMENTATIONS = [
        (DARAJA, 'Daraja'),
        (KOPOKOPO, 'Kopokopo'),
    ]
    organization = models.OneToOneField(Organization, on_delete=models.CASCADE)
    implementation = models.PositiveSmallIntegerField(
        choices=IMPLEMENTATIONS, default=None)
    business_short_code = models.CharField(
        max_length=20, null=True, blank=True)
    consumer_key = models.CharField(max_length=300, null=True, blank=True)
    consumer_secret = models.CharField(max_length=300, null=True, blank=True)
    pass_key = models.CharField(max_length=300, null=True, blank=True)
    client_id = models.CharField(max_length=300, null=True, blank=True)
    client_secret = models.CharField(max_length=300, null=True, blank=True)
    till_number = models.CharField(max_length=20, null=True, blank=True)

organization/forms.py
from django import forms
from django.forms import ModelForm

from .models import OrganizationSmsProvider, OrganizationMpesaDetails

class AddSmsGatewayForm(ModelForm):
    provider = forms.ChoiceField(label='Provider', choices=OrganizationSmsProvider.PROVIDERS,
                               widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Provider'}))
    sender_id = forms.CharField(max_length=150, label='Sender id',
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Sender id'}))
    api_key = forms.CharField(required=False, max_length=200, label='Api key',
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'api key' }))
    username = forms.CharField(required=False, max_length=150, label='Username',
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    base_url = forms.URLField(required=False, max_length=200, label='Base url',
                               widget=forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'base url'}))
    api_secret = forms.CharField(required=False, max_length=200, label='Api secret',
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Api secret'}))
    account_sid = forms.CharField(required=False, max_length=200, label='Account SID',
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'account sid'}))
    auth_token = forms.CharField(required=False, max_length=200, label='Auth token',
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Auth token'}))
    phone_number = forms.CharField(required=False, max_length=200, label='Phone _number',
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '254712345670'}))
    class Meta:
        model = OrganizationSmsProvider
        exclude = ['verified']
        widgets = {
            'organization': forms.HiddenInput(),
            'verification_code': forms.HiddenInput()
            }


class SmsDetailsVerificationForm(forms.ModelForm):
    verification_code = forms.CharField(max_length=150, label='verification code',
                               widget=forms.TextInput(attrs={'class': 'form-control with-border', 'placeholder': 'verification code'}))
    class Meta:
        model = OrganizationSmsProvider
        fields = ['verification_code']


class AddMpesaDetailsForm(forms.ModelForm):
    implementation = forms.ChoiceField(label='Implementation', choices=OrganizationMpesaDetails.IMPLEMENTATIONS,
                               widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Provider'}))
    business_short_code = forms.CharField(required=False, max_length=20, label='Business short code',
                                widget=forms.TextInput(attrs={'class': 'form-control with-border', 'placeholder': 'Short code'}))
    consumer_key = forms.CharField(required=False, max_length=300, label='Consumer key',
                                widget=forms.TextInput(attrs={'class': 'form-control with-border', 'placeholder': 'Consumer key'}))
    consumer_secret = forms.CharField(required=False, max_length=300, label='Consumer secret',
                                widget=forms.TextInput(attrs={'class': 'form-control with-border', 'placeholder': 'consumer secret'}))
    pass_key = forms.CharField(required=False, max_length=300, label='Pass key',
                                widget=forms.TextInput(attrs={'class': 'form-control with-border', 'placeholder': 'Pass key'}))
    # phone_number = forms.CharField(required=False, max_length=300, label='Phone number',
    #                             widget=forms.TextInput(attrs={'class': 'form-control with-border', 'placeholder': '254712345678'}))
    client_id = forms.CharField(required=False, max_length=300, label='Client Id',
                                widget=forms.TextInput(attrs={'class': 'form-control with-border', 'placeholder': 'client id'}))
    client_secret = forms.CharField(required=False, max_length=300, label='Client secret',
                                widget=forms.TextInput(attrs={'class': 'form-control with-border', 'placeholder': 'client secret'}))
    till_number = forms.CharField(required=False, max_length=20, label='Till number',
                                widget=forms.TextInput(attrs={'class': 'form-control with-border', 'placeholder': 'kopo kopo till'}))
    class Meta:
        model =OrganizationMpesaDetails
        fields = '__all__'
        widgets = {'organization': forms.HiddenInput()}
        

api/organizations/views.py
from django.shortcuts import render
from rest_framework import viewsets
from .serializers import DriversSerializer, OrganizationSerializer

# Create your views here.
class DriversViewSet(viewsets.ModelViewSet):
    queryset = Drivers.objects.order_by("-created_at")
    serializer_class = DriversSerializer
    permission_classes = []
    authentication_classes = []

templates/organization/create.html
{% extends "base.html" %}{% load static %}
{% block title %} Drivers {% endblock %}
{% block styles %} 
<link rel="stylesheet" href="{% static "theme/css/jquery.datetimepicker.min.css" %}">
<link rel="stylesheet" href="{% static "theme/css/form.css" %}">
{% endblock %}

{% block content %}
<div>			

	<!-- Row -->
	<div class="row">
		<div class="col-xl-12">
			<div class="dashboard-box margin-top-0">


				<div class="content with-padding padding-bottom-10">

					<div class="row">
						<div class="col-xl-12">
						{% for field in form %}
						  {% if field.errors %}
							{% for error in field.errors %}
							<div class="alert alert-danger alert-dismissible fade show" role="alert">
							  {{ error }}
							  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
							</div>
							{% endfor %}
						  {% endif %}
						{% endfor %}	
						</div>
					</div>


<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-11 col-sm-9 col-md-7 col-lg-6 col-xl-5 text-center p-0 mt-3 mb-2">
            <div class="card px-0 pt-4 pb-0 mt-3 mb-3">
                <h2 id="heading">Create a driver</h2>
                <p>Fill out the form below to create a new driver</p>
                <form id="msform">
                    <fieldset>
                        <div class="form-card">
                            <div class="row">
                                <div class="col-xl-7">
                                    <h2 class="fs-title">Driver details</h2>
                                </div>
                            </div> 

							<div class="row">
								<div class="col-xl-12" id="step1-errors">
								</div>
							</div>



							<div class="submit-field">
								<div class="row">
									<div class="col-xl-12">
										<h6>Full names</h6>
										<div class="submit-field">
											<input type="text" class="with-border" id="name">
										</div>
									</div>
									<div class="col-xl-12">
										<h6>Phone number</h6>
										<div class="submit-field">
											<input type="number" class="with-border" id="phonenumber">
										</div>
									</div>
								</div>
							</div>



                        </div> <input type="button" id="form-submit" name="next" class="next action-button" value="Submit"/>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>


				</div>

			</div>
		</div>

	</div>
	<!-- Row / End -->

</div>
<form action="" method="post" style="display:none" id="form-hidden">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% endblock content %}
{% block scripts %}
<script>
  $(document).ready(function() {
     $("#form-submit").click(function(event) {
        event.preventDefault();

		var inp = $('#phonenumber').val();
		if(inp == undefined || $.trim(inp).length < 1){
			var error = `
				<div class="alert alert-danger alert-dismissible fade show" role="alert">
				 Invalid phone number
				  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
				</div>
			`;
			$('#step1-errors').html(error);
			return;
		}
		$('#id_phone_number').val($.trim(inp));

		var inp = $('#name').val();
		if(inp == undefined || $.trim(inp).length < 1){
			var error = `
				<div class="alert alert-danger alert-dismissible fade show" role="alert">
				 Invalid driver name
				  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
				</div>
			`;
			$('#step1-errors').html(error);
			return;
		}
		$('#id_name').val($.trim(inp));
		$('#form-hidden').submit();
     });
  });
</script>
{% endblock scripts %}

templates/organization/detail.html
{% extends "base.html" %}
{% block title %} Dashboard {% endblock %}
{% block content %}
<form action="" method="post">
<div>

	<!-- Dashboard Headline -->
	<div class="dashboard-headline">
		<h3>Hi, {{ request.user.first_name }}!</h3>
	</div>


	<!-- Row -->
	<div class="row">

		<div class="col-xl-12">
			<div class="dashboard-box margin-top-0">

				<!-- Headline -->
				<div class="headline">
					<h3><i class="icon-material-outline-business"></i> {{ object.name }} - {{ object.country }}</h3>
				</div>

				<div class="content with-padding padding-bottom-20">

					<div class="row">

						<div class="col">
							<div class="row">

								<div class="col-xl-6">
									<h5>Details</h5>
									<span>{{ object.owner.email }}</span>
								</div>

								<div class="col-xl-6">
									<h5>Created</h5>
									<span>{{ object.created|date:'d M, Y H:i' }}</span>
								</div>

							</div>
						</div>
					</div>

				</div>
			</div>
		</div>

		<div class="col-xl-12">
			<div class="dashboard-box margin-top-20">

				<!-- Headline -->
				<div class="headline">
					<h3><i class="icon-feather-users"></i> Members</h3>
					<div class="buttons-to-right"><a class="dashboard-status-button blue" href="{% url 'organization:add-user' %}">Add member</a></div>
				</div>

				<div class="content with-padding padding-bottom-20">

					<div class="row">

						<div class="col">
							<div class="row">
						{% for member in object.members %}

								<div class="col-xl-12">

									<div class="job-listing">
										<!-- Job Listing Details -->
										<div class="job-listing-details">

											<!-- Details -->
											<div class="job-listing-description">
												<h3 class="job-listing-title">{{ member.user.first_name }} {{member.user.last_name }} {% if member.user == object.owner %} <span class="capitalize dashboard-status-button green">owner</span>{% else %} <span class="capitalize dashboard-status-button yellow">member</span> 			&nbsp;&nbsp;<a href="{% url 'organization:remove-user' member.pk %}" rel="superbox[iframe]" class="remove">Remove</a>{% endif %} </h3>

												<!-- Job Listing Footer -->
												<div class="job-listing-footer">
													<ul>
														<li><i class="icon-material-outline-email"></i> {{ member.user.email }}</li>
														<li><i class="icon-material-outline-access-time"></i> Member since {{ member.created|date:'d M, Y H:i' }}</li>
													</ul>
												</div>
											</div>
										</div>

									</div>

								</div>
						{% endfor %}


							</div>
						</div>
					</div>

				</div>
			</div>
		</div>

		<div class="col-xl-12">
			<div class="dashboard-box margin-top-20">

				<!-- Headline -->
				<div class="headline">
					<h3><i class="icon-line-awesome-money"></i> Mpesa details</h3>
					<div class="buttons-to-right"><a class="dashboard-status-button blue" href="{% url 'organization:add-m-details' %}">Add mpesa details</a></div>
				</div>

				<div class="content with-padding padding-bottom-20">

					<div class="row container-fluid">

						<div class="col">
							<div class="row">
								<div class="col-xl-6">
									<h5>Business shortcode:</h5>
									<span>{{ object.mpesa_details.business_short_code }}</span>
								</div>
							</div>
							<div class="row">
								<div class="col-xl-6">
									<h5>Consumer key:</h5>
									<span>{{ object.mpesa_details.consumer_key }}</span>
								</div>
							</div>
							<div class="row">
								<div class="col-xl-6">
									<h5>Consumer Secret:</h5>
									<span>{{ object.mpesa_details.consumer_secret }}</span>
								</div>
							</div>
							<div class="row">
								<div class="col-xl-12">
									<h5>Pass key:</h5>
									<span>{{ object.mpesa_details.pass_key }}</span>
								</div>
							</div>
						</div>
					</div>

				</div>
			</div>
		</div>

		<div class="col-xl-12">
			<div class="dashboard-box margin-top-20">

				<!-- Headline -->
				<div class="headline">
					<h3><i class="icon-material-outline-textsms"></i> SMS Settings</h3>
					<div class="buttons-to-right"><a class="dashboard-status-button blue" href="{% url 'organization:add_sms_gateway' %}">Add sms gateway</a></div>
				</div>

				<div class="content with-padding padding-bottom-20">

					<div class="row">

						<div class="col">
							<div class="row">

								<div class="col-xl-12">
									<div class="checkbox">
										<input type="checkbox" name="order_recieved" {% if object.send_order_received_sms %}checked{% endif %} id="order_recieved" >
										<label for="order_recieved"><span class="checkbox-icon"></span> Send SMS when and order is uploaded</label>
									</div>
								</div>

								<div class="col-xl-12">
									<div class="checkbox">
										<input type="checkbox" name="driver_assigned" {% if object.send_driver_assign_sms %}checked{% endif %} id="driver_assigned" >
										<label for="driver_assigned"><span class="checkbox-icon"></span> Send SMS when a driver is assgined</label>
									</div>
								</div>

								<div class="col-xl-12">
									<div class="checkbox">
										<input type="checkbox" name="driver_reassigned" {% if object.send_driver_reassign_sms %}checked{% endif %} id="driver_reassigned" >
										<label for="driver_reassigned"><span class="checkbox-icon"></span> Send SMS when a driver is reassigned</label>
									</div>
								</div>


								<div class="col-xl-12">
									<div class="checkbox">
										<input type="checkbox" name="driver_started" {% if object.send_driver_start_sms %}checked{% endif %} id="driver_started">
										<label for="driver_started"><span class="checkbox-icon"></span> Send SMS when a driver starts delivery</label>
									</div>
								</div>

								<div class="col-xl-12">
									<div class="checkbox">
										<input type="checkbox" name="order_completed" {% if object.send_driver_complete_sms %}checked{% endif %} id="order_completed">
										<label for="order_completed"><span class="checkbox-icon"></span> Send SMS when an order is completed *(if unchecked, your customers will not be able to leave a review)</label>
									</div>
								</div>

							</div>
						</div>
					</div>

				</div>
			</div>
		</div>

		<div class="col-xl-12">
			<div class="dashboard-box margin-top-20">

				<!-- Headline -->
				<div class="headline">
					<h3><i class="icon-material-outline-assignment"></i>Order Assigning</h3>
				</div>

				<div class="content with-padding padding-bottom-20">

					<div class="row">

						<div class="col">
							<div class="row">

								<div class="col-xl-12">
									<div class="checkbox">
										<input type="checkbox" name="allow_driver_to_self_assign_orders" {% if object.allow_driver_to_self_assign_orders %}checked{% endif %} id="id_allow_driver_to_self_assign_orders" >
										<label for="id_allow_driver_to_self_assign_orders"><span class="checkbox-icon"></span> Allow drivers to self assign orders</label>
									</div>
								</div>
							</div>
						</div>
					</div>

				</div>
			</div>
		</div>

		<div class="col-xl-12">
			<div class="dashboard-box margin-top-20">

				<!-- Headline -->
				<div class="headline">
					<h3><i class="icon-material-outline-settings-input-component"></i> Callback URL</h3>
				</div>

				<div class="content with-padding padding-bottom-20">

					<div class="row">

						<div class="col">
							<div class="row">

								<div class="col-xl-12">
									<input type="text" class="input-text with-border" name="callback_url" id="callback_url" placeholder="Enter your callback URL" value="{% if object.callback_url %}{{  object.callback_url }}{% endif %}">
								</div>

							</div>
						</div>
					</div>

				</div>
			</div>
		</div>

		<div class="col-xl-12">
			<div class="dashboard-box margin-top-20">

				<!-- Headline -->
				<div class="headline">
					<h3><i class="icon-material-outline-map"></i> Google maps api key</h3>
				</div>

				<div class="content with-padding padding-bottom-20">

					<div class="row">

						<div class="col">
							<div class="row">

								<div class="col-xl-12">
									<input type="text" class="input-text with-border" name="googlemap_api_key" id="googlemap_api_key" placeholder="Enter Google map api key" value="{% if object.googlemap_api_key %}{{  object.googlemap_api_key }}{% endif %}">
								</div>

							</div>
						</div>
					</div>

				</div>
			</div>
		</div>

		<!-- Button -->
		<div class="col-xl-12">
			<button type="submit" class="button ripple-effect big margin-top-30">Save Changes</button>
		</div>

	</div>
	<!-- Row / End -->
</div>
{% csrf_token %}
</form>
{% endblock content %}