PROJECT/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView
from organization.views import DashboardView
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(DashboardView.as_view()), name='dashboard'),
	path('order/', include(('order.urls', 'order'), namespace='order')),
	path('route/', include(('route.urls', 'route'), namespace='route')),
	path('driver/', include(('driver.urls', 'driver'), namespace='driver')),
	path('vehicle/', include(('vehicle.urls', 'order'), namespace='vehicle')),
	path('accounts/', include(('user.urls', 'accounts'), namespace='accounts')),
	path('organizations/', include(('organization.urls', 'organization'), namespace='organization')),

    path('api/v1/', include('api.urls')),
    #path('', RedirectView.as_view(url=reverse_lazy('organizations:index')), name='home'),
]

api/urls.py
from django.urls import path, include

urlpatterns = [
    path("user/", include("api.user.urls")),
    path("order/", include("api.order.urls")),
    # Uses custom token
    path("driver/", include("api.driver.urls")),
    path("appointments/", include("api.appointments.urls")),
    # path("organizations/", include("api.organizations.urls")),
]

order/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

urlpatterns = [
    path('track/<str:public_id>', views.ReviewView.as_view(), name='track'),
    path('review/<str:public_id>', views.ReviewView.as_view(), name='review'),

    path('', login_required(views.IndexView.as_view()), name='index'),
    path('map', login_required(views.MapView.as_view()), name='map'),
    path('plan', login_required(views.PlanView.as_view()), name='plan'),
    path('json', login_required(views.OrdersJsonView.as_view()), name='json'),
    path('create', login_required(views.CreateView.as_view()), name='create'),
    path('<int:pk>', login_required(views.OrderView.as_view()), name='detail'),
    path('reviews', login_required(views.ReviewsView.as_view()), name='reviews'),
    path('export', login_required(views.ExportOrdersView.as_view()), name='export'),
    path('payments', login_required(views.PaymentsView.as_view()), name='payments'),
    path('track', login_required(views.OrderTrackingIframeView.as_view()), name='track'),
    path('route/json', login_required(views.RouteJsonView.as_view()), name='route-json'),
    path('<int:pk>/partial', login_required(views.OrderPartialView.as_view()), name='detail-partial'),
    path('export/reviews', login_required(views.ExportReviewsView.as_view()), name='export-reviews'),
    path('upload/iframe', login_required(views.UploadOrdersIframeView.as_view()), name='upload-iframe'),
    path('state/<int:pk>/iframe', login_required(views.StateIframeView.as_view()), name='state-iframe'),
    path('assign/<int:pk>/iframe', login_required(views.AssignIframeView.as_view()), name='assign-iframe'),
    path('pickup/<int:pk>/iframe', login_required(views.PickupIframeView.as_view()), name='pickup-iframe'),
    path('dropoff/<int:pk>/iframe', login_required(views.DropoffIframeView.as_view()), name='dropoff-iframe'),
    path('multi-assign/iframe', login_required(views.MultiAssignIframeView.as_view()), name='multi-assign-iframe'),
    path('ajax-assign/iframe', login_required(views.AjaxAssignIframeView.as_view()), name='ajax-assign-iframe'),
    path('export/driver/reviews', login_required(views.ExportDriverReviewsView.as_view()), name='export-driver-reviews'),
    path('ajax-assign/iframe/<int:vehicle_id>/<int:route_id>', login_required(views.AjaxAssignIframeView.as_view()), name='ajax-assign-iframe'),
]

templates/base.html
{% load static %}{% load display_organizations %}<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<link rel="icon" href="{% static "theme/images/getboda-logo.png" %}">
	<title>Getboda - {% block title %}{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- CSS
	================================================== -->
	<link rel="stylesheet" href="{% static "theme/css/bootstrap.min.css" %}">
	<link rel="stylesheet" href="{% static "theme/css/style.css" %}?v=1">
	<link rel="stylesheet" href="{% static "theme/css/colors/blue.css" %}">
	<link rel="stylesheet" href="{% static "theme/css/daterangepicker.css" %}">
	<link rel="stylesheet" href="{% static "theme/css/jquery.superbox.css" %}">
	<link rel="stylesheet" href="{% static "theme/css/custom.css" %}">

{% block styles %} {% endblock %}
</head>
<body class="gray">

<!-- Wrapper -->
<div id="wrapper">

<!-- Header Container
================================================== -->
<header id="header-container" class="fullwidth dashboard-header not-sticky">

	<!-- Header -->
	<div id="header">
		<div class="container">

			<!-- Left Side Content -->
			<div class="left-side">

				<!-- Logo -->
				<div id="logo">
					<a href="/"><img src="{% static "theme/images/getboda-horizontal.png" %}" alt=""></a>
				</div>

				<!-- Main Navigation -->
				<nav id="navigation">
				</nav>
				<div class="clearfix"></div>
				<!-- Main Navigation / End -->

			</div>
			<!-- Left Side Content / End -->


			<!-- Right Side Content / End -->

			<!-- Right Side Content / End -->
			<div class="right-side">
				{% display_organizations request %}
			</div>
			<!-- Right Side Content / End -->

		</div>
	</div>
	<!-- Header / End -->

</header>
<div class="clearfix"></div>
<!-- Header Container / End -->


<!-- Dashboard Container -->
<div class="dashboard-container">

	<!-- Dashboard Sidebar
	================================================== -->
	<div class="dashboard-sidebar">
		<div class="dashboard-sidebar-inner" data-simplebar>
			<div class="dashboard-nav-container">

				<!-- Responsive Navigation Trigger -->
				<a href="#" class="dashboard-responsive-nav-trigger">
					<span class="hamburger hamburger--collapse" >
						<span class="hamburger-box">
							<span class="hamburger-inner"></span>
						</span>
					</span>
					<span class="trigger-title">Navigation</span>

				</a>

				<!-- Navigation -->
				<div class="dashboard-nav">
					<div class="dashboard-nav-inner">
						<ul data-submenu-title="">
							<li><a href="{% url 'dashboard' %}"><i class="icon-material-outline-assignment"></i> Dashboard</a></li>
						</ul>
						<ul data-submenu-title="Orders">
							<li><a href="{% url 'order:create' %}"><i class="icon-material-outline-library-add"></i> New </a></li>
							<li><a href="{% url 'order:index' %}"><i class="icon-material-outline-assignment"></i> Manage</a></li>
							<li><a href="{% url 'order:reviews' %}"><i class="icon-material-outline-rate-review"></i> Reviews</a></li>
							<li><a href="{% url 'order:payments' %}"><i class="icon-line-awesome-money"></i> Payments</a></li>
						</ul>

						<ul data-submenu-title="Drivers">
							<li><a href="{% url 'driver:create' %}"><i class="icon-material-outline-library-add"></i> New </a></li>
							<li><a href="{% url 'driver:index' %}"><i class="icon-line-awesome-bicycle"></i> Manage </a></li>
						</ul>

					</div>
				</div>
				<!-- Navigation / End -->

			</div>
		</div>
	</div>
	<!-- Dashboard Sidebar / End -->


	<!-- Dashboard Content
	================================================== -->
	<div class="dashboard-content-container"  data-simplebar="init">
		<div class="simplebar-track vertical" style="visibility: visible;"><div class="simplebar-scrollbar visible" style="visibility: visible; top: 0px; height: 185px;"></div></div>
		<div class="simplebar-track horizontal" style="visibility: visible;"><div class="simplebar-scrollbar visible" style="visibility: visible; left: 0px; width: 25px;"></div></div>

		<div class="simplebar-scroll-content" style="padding-right: 15px; margin-bottom: -30px;">
			<div class="simplebar-content" style="padding-bottom: 15px; margin-right: -15px;">

				<div class="dashboard-content-inner" >

					<div class="row">
						<div class="col-md-12">
							<div class="col-xl-5 offset-xl-3">
								{% for message in messages %}
									{% if message.tags == 'error' %}
								<div class="alert alert-danger alert-dismissible fade show" role="alert">
								 {{ message |safe }}
								  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
								</div>
									{% else %}
								<div class="alert alert-{{ message.tags }}  alert-dismissible fade show" role="alert">
								 {{ message|safe }}
								  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
								</div>
									{% endif %}
								{% endfor %}
							</div>
							{% block titlebar %} {% endblock %}
						</div>
					</div>
					<div class="row">
						{% block content %} {% endblock %}
					</div>


					<!-- Footer -->
					<div class="dashboard-footer-spacer"></div>
					<div class="small-footer margin-top-15">
						<div class="small-footer-copyrights">
							<p class="footer-links text-center">Designed and Developed by <a class="grey" href="https://www.getboda.co.ke/">Getboda Technology
						</div>
						<div class="clearfix"></div>
					</div>
					<!-- Footer / End -->

				</div>
			</div>
		</div>
	</div>
	<!-- Dashboard Content / End -->

</div>
<!-- Dashboard Container / End -->

</div>
<!-- Wrapper / End -->




<!-- Scripts
================================================== -->
<script src="{% static "theme/js/jquery-3.4.1.min.js" %}"></script>
<script src="{% static "theme/js/jquery-migrate-3.1.0.min.js" %}"></script>
<script src="{% static "theme/js/mmenu.min.js" %}"></script>
<script src="{% static "theme/js/tippy.all.min.js" %}"></script>
<script src="{% static "theme/js/simplebar.min.js" %}"></script>
<script src="{% static "theme/js/bootstrap.bundle.min.js" %}"></script>
<script src="{% static "theme/js/bootstrap-slider.min.js" %}"></script>
<script src="{% static "theme/js/bootstrap-select.min.js" %}"></script>
<script src="{% static "theme/js/snackbar.js" %}"></script>
<script src="{% static "theme/js/clipboard.min.js" %}"></script>
<script src="{% static "theme/js/counterup.min.js" %}"></script>
<script src="{% static "theme/js/magnific-popup.min.js" %}"></script>
<script src="{% static "theme/js/slick.min.js" %}"></script>
<script src="{% static "theme/js/custom.js" %}"></script>
<script src="{% static "theme/js/moment.min.js" %}"></script>
<script src="{% static "theme/js/daterangepicker.min.js" %}"></script>
<script src="{% static "theme/js/jquery.superbox-min.js" %}"></script>
<script type="text/javascript">
jQuery.browser = {};
(function () {
    jQuery.browser.msie = false;
    jQuery.browser.version = 0;
    if (navigator.userAgent.match(/MSIE ([0-9]+)\./)) {
        jQuery.browser.msie = true;
        jQuery.browser.version = RegExp.$1;
    }
})();
$(function(){
	$.superbox.settings = {
		boxId: "superbox", // Id attribute of the "superbox" element
		boxClasses: "", // Class of the "superbox" element
		overlayOpacity: .8, // Background opaqueness
		boxWidth: parseInt(window.innerWidth*0.90), // Default width of the box
		boxHeight: parseInt(window.innerHeight*0.90), // Default height of the box
		loadTxt: "Loading...", // Loading text
		closeTxt: "Close", // "Close" button text
		prevTxt: "Previous", // "Previous" button text
		nextTxt: "Next" // "Next" button text
	};
	$.superbox();
});
var wsOrders = new WebSocket(ws_connection_url);

// Main function which handles the connection
// of websocket.

function connect() {
	  let lastBell = null;
    wsOrders.onopen = function open() {
        console.log('WebSockets connection created.');
    };

    wsOrders.onclose = function (e) {
        console.log('Socket is closed. Reconnect will be attempted in 1 second.', e.reason);
        setTimeout(function () {
            connect();
        }, 1000);
    };
    // Sending the info about the room
    wsOrders.onmessage = function (e) {
        // On getting the message from the server
        // Do the appropriate steps on each event.
    let data = JSON.parse(e.data);
		var audio = new Audio('{% static "sounds/alert.mp3" %}');
		if(lastBell == null || (Date.now() - lastBell) > 3000  ){
			audio.play();
			lastBell = Date.now();
		}

		var action =  data.action;
		var order_id =  data.order_id;
		var snackbar_text = ''
		if(action == 'order_created'){
			snackbar_text = `New order #${order_id} have been created`;

			if ($("#ws-orders").length > 0){
			  $.ajax({url: `/order/${order_id}/partial`, success: function(result){
				$("#ws-orders").prepend(result);
				$('.do-blink').hover(
					function(){ $(this).removeClass('do-blink') }
				);
			  }});
			}
		} else if(action == 'order_updated'){
			snackbar_text = `Order #${order_id} have been updated`;
			div = `#order-${order_id}`;
			if ($("#ws-orders").length > 0 && $(div).length > 0){
			  $.ajax({url: `/order/${order_id}/partial`, success: function(result){
				$( div ).replaceWith( result );
				$('.do-blink').hover(
					function(){ $(this).removeClass('do-blink') }
				);
			  }});
			}
		}
		Snackbar.show({text: snackbar_text});
    };

    if (wsOrders.readyState == WebSocket.OPEN) {
        wsOrders.onopen();
    }
}
connect();

</script>
{% block scripts %} {% endblock %}

</body>
</html>

templates/base0.html
{% load static %}<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Getboda - {% block title %}{% endblock %}</title>
	<link rel="icon" href="{% static "theme/images/getboda-logo.png" %}">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<!-- CSS
	================================================== -->
	<link rel="stylesheet" href="{% static "theme/css/bootstrap.min.css" %}">
	<link rel="stylesheet" href="{% static "theme/css/style.css" %}?v=1">
	<link rel="stylesheet" href="{% static "theme/css/colors/blue.css" %}">
	<link rel="stylesheet" href="{% static "theme/css/custom.css" %}">

</head>
<body>

<!-- Wrapper -->
<div id="wrapper">


<div class="clearfix"></div>
<!-- Header Container / End -->

<!-- Titlebar
================================================== -->
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="col-xl-5 offset-xl-3">
				{% for message in messages %}
					{% if message.tags == 'error' %}
				<div class="alert alert-danger alert-dismissible fade show" role="alert">
				 {{ message |safe }}
				  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
				</div>
					{% else %}
				<div class="alert alert-{{ message.tags }}  alert-dismissible fade show" role="alert">
				 {{ message|safe }}
				  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
				</div>
					{% endif %}
				{% endfor %}				
			</div>
			{% block titlebar %} {% endblock %}
		</div>
	</div>
</div>


<!-- Page Content
================================================== -->
<div class="container holder min-height">
	<div class="row">
		<div class="welcome-text">
			<a href="https://www.getboda.co.ke/"><img src="{% static "theme/images/getboda-horizontal.png" %}" alt=""></a>
		</div>
	</div>

	<div class="row">
		{% block content %} {% endblock %}
	</div>
</div>


<!-- Spacer -->
<div class="margin-top-70"></div>
<!-- Spacer / End-->

<!-- Footer
================================================== -->
<div id="footer">
	<!-- Footer Copyrights -->
	<div class="footer-bottom-section">
		<div class="container">
			<div class="row">
				<div class="col-xl-12">
					<p class="footer-links text-center">Designed and Developed by <a class="grey" href="https://www.getboda.co.ke/">Getboda Technology</a></p>
				</div>
			</div>
		</div>
	</div>
	<!-- Footer Copyrights / End -->

</div>
<!-- Footer / End -->

</div>
<!-- Wrapper / End -->

<!-- Scripts
================================================== -->
<script src="{% static "theme/js/jquery-3.4.1.min.js" %}"></script>
<script src="{% static "theme/js/jquery-migrate-3.1.0.min.js" %}"></script>
<script src="{% static "theme/js/mmenu.min.js" %}"></script>
<script src="{% static "theme/js/tippy.all.min.js" %}"></script>
<script src="{% static "theme/js/simplebar.min.js" %}"></script>
<script src="{% static "theme/js/bootstrap.bundle.min.js" %}"></script>
<script src="{% static "theme/js/bootstrap-slider.min.js" %}"></script>
<script src="{% static "theme/js/bootstrap-select.min.js" %}"></script>
<script src="{% static "theme/js/snackbar.js" %}"></script>
<script src="{% static "theme/js/clipboard.min.js" %}"></script>
<script src="{% static "theme/js/counterup.min.js" %}"></script>
<script src="{% static "theme/js/magnific-popup.min.js" %}"></script>
<script src="{% static "theme/js/slick.min.js" %}"></script>
<script src="{% static "theme/js/custom.js" %}"></script>
{% block scripts %} {% endblock %}
</body>
</html>

templates/base_full.html
{% load static %}{% load display_organizations %}<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<link rel="icon" href="{% static "theme/images/getboda-logo.png" %}">
	<title>Getboda - {% block title %}{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
	<script src="{% static "theme/js/markerclusterer.js" %}"></script>

	<!-- CSS
	================================================== -->
	
	<!-- CSS
	================================================== -->
	<link rel="stylesheet" href="{% static "theme/css/daterangepicker.css" %}">
	<link rel="stylesheet" href="{% static "theme/css/jquery.superbox.css" %}">
	<link rel="stylesheet" href="{% static "theme/css/bootstrap.min.css" %}">
	<link rel="stylesheet" href="{% static "theme/css/style.css" %}">
	<link rel="stylesheet" href="{% static "theme/css/colors/blue.css" %}">
	<link rel="stylesheet" href="{% static "theme/css/custom.css" %}">
	<style type="text/css">
		/* Always set the map height explicitly to define the size of the div
		* element that contains the map. */
		#map {
			height: 100%;
		}
		/* Optional: Makes the sample page fill the window. */
		html,
		body {
			height: 100%;
			margin: 0;
			padding: 0;
		}
	</style>


{% block styles %} {% endblock %}
</head>
<body class="gray">

<!-- Wrapper -->
<div id="wrapper">

<!-- Header Container
================================================== -->
<header id="header-container" class="fullwidth dashboard-header not-sticky">

	<!-- Header -->
	<div id="header">
		<div class="container">
			
			<!-- Left Side Content -->
			<div class="left-side">
				
				<!-- Logo -->
				<div id="logo">
					<a href="/"><img src="{% static "theme/images/getboda-horizontal.png" %}" alt=""></a>
				</div>

				<!-- Main Navigation -->
				<nav id="navigation">
				</nav>
				<div class="clearfix"></div>
				<!-- Main Navigation / End -->
				
			</div>
			<!-- Left Side Content / End -->


			<!-- Right Side Content / End -->

			<!-- Right Side Content / End -->
			<div class="right-side">
				{% display_organizations request %}
			</div>
			<!-- Right Side Content / End -->

		</div>
	</div>
	<!-- Header / End -->

</header>
<div class="clearfix"></div>
<!-- Header Container / End -->


<!-- Dashboard Container -->
<div class="dashboard-container">

	<!-- Dashboard Content
	================================================== -->
	<div class="dashboard-content-container"  data-simplebar="init">
		<div class="simplebar-track vertical" style="visibility: visible;"><div class="simplebar-scrollbar visible" style="visibility: visible; top: 0px; height: 185px;"></div></div>
		<div class="simplebar-track horizontal" style="visibility: visible;"><div class="simplebar-scrollbar visible" style="visibility: visible; left: 0px; width: 25px;"></div></div>

		<div class="simplebar-scroll-content" style="padding-right: 15px; margin-bottom: -30px;">
			<div class="simplebar-content" style="padding-bottom: 15px; margin-right: -15px;">

				<div class="dashboard-content-inner--" >
					
					<div class="row">
						<div class="col-md-12">
							<div class="col-xl-5 offset-xl-3">
								{% for message in messages %}
									{% if message.tags == 'error' %}
								<div class="alert alert-danger alert-dismissible fade show" role="alert">
								 {{ message |safe }}
								  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
								</div>
									{% else %}
								<div class="alert alert-{{ message.tags }}  alert-dismissible fade show" role="alert">
								 {{ message|safe }}
								  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
								</div>
									{% endif %}
								{% endfor %}				
							</div>
							{% block titlebar %} {% endblock %}
						</div>
					</div>
					<div class="row">
						{% block content %} {% endblock %}
					</div>

<!--
					<!-- Footer -->
					<div class="small-footer">
						<div class="small-footer-copyrights">
							<p class="footer-links text-center">Designed and Developed by <a class="grey" href="https://www.getboda.co.ke/">Getboda Technology
						</div>
						<div class="clearfix"></div>
					</div>
					<!-- Footer / End -->
					

				</div>
			</div>
		</div>
	</div>
	<!-- Dashboard Content / End -->

</div>
<!-- Dashboard Container / End -->

</div>
<!-- Wrapper / End -->




<!-- Scripts
================================================== -->
<script src="{% static "theme/js/jquery-3.4.1.min.js" %}"></script>
<script src="{% static "theme/js/jquery-migrate-3.1.0.min.js" %}"></script>
<script src="{% static "theme/js/mmenu.min.js" %}"></script>
<script src="{% static "theme/js/tippy.all.min.js" %}"></script>
<script src="{% static "theme/js/simplebar.min.js" %}"></script>
<script src="{% static "theme/js/bootstrap.bundle.min.js" %}"></script>
<script src="{% static "theme/js/bootstrap-slider.min.js" %}"></script>
<script src="{% static "theme/js/bootstrap-select.min.js" %}"></script>
<script src="{% static "theme/js/snackbar.js" %}"></script>
<script src="{% static "theme/js/clipboard.min.js" %}"></script>
<script src="{% static "theme/js/counterup.min.js" %}"></script>
<script src="{% static "theme/js/magnific-popup.min.js" %}"></script>
<script src="{% static "theme/js/slick.min.js" %}"></script>
<script src="{% static "theme/js/custom.js" %}"></script>
<script src="{% static "theme/js/moment.min.js" %}"></script>
<script src="{% static "theme/js/daterangepicker.min.js" %}"></script>
<script src="{% static "theme/js/jquery.superbox-min.js" %}"></script>
<script type="text/javascript">
jQuery.browser = {};
(function () {
    jQuery.browser.msie = false;
    jQuery.browser.version = 0;
    if (navigator.userAgent.match(/MSIE ([0-9]+)\./)) {
        jQuery.browser.msie = true;
        jQuery.browser.version = RegExp.$1;
    }
})();
$(function(){
	$.superbox.settings = {
		boxId: "superbox", // Id attribute of the "superbox" element
		boxClasses: "", // Class of the "superbox" element
		overlayOpacity: .8, // Background opaqueness
		boxWidth: parseInt(window.innerWidth*0.90), // Default width of the box
		boxHeight: parseInt(window.innerHeight*0.90), // Default height of the box
		loadTxt: "Loading...", // Loading text
		closeTxt: "Close", // "Close" button text
		prevTxt: "Previous", // "Previous" button text
		nextTxt: "Next" // "Next" button text
	};
	$.superbox();
});
</script>
{% block scripts %} {% endblock %}

</body>
</html>

templates/base_map.html
{% load static %}<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<link rel="icon" href="{% static "theme/images/getboda-logo.png" %}">
	<title>Getboda - {% block title %}{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
	<script src="{% static "theme/js/markerclusterer.js" %}"></script>

	<!-- CSS
	================================================== -->
	<link rel="stylesheet" href="{% static "theme/css/bootstrap.min.css" %}">
	<link rel="stylesheet" href="{% static "theme/css/style.css" %}">
	<link rel="stylesheet" href="{% static "theme/css/colors/blue.css" %}">
	<link rel="stylesheet" href="{% static "theme/css/custom.css" %}">
	<style type="text/css">
		/* Always set the map height explicitly to define the size of the div
		* element that contains the map. */
		#map {
			height: 100%;
		}
		/* Optional: Makes the sample page fill the window. */
		html,
		body {
			height: 100%;
			margin: 0;
			padding: 0;
		}
	</style>
	{% block styles %} {% endblock %}
	{% block content %} {% endblock %}
	{% block scripts %} {% endblock %}
</head>
<body class="gray">
	<div id="map"></div>
	<script
	src="https://maps.googleapis.com/maps/api/js?key={% if map_api %}{{map_api}}{% else %}AIzaSyDrEYEy6nXlouW4TCD_r3sGs44MwHAS3z4{% endif %}&callback=initMap&libraries=geometry&v=weekly"
	async></script>

	<h1>map#{{map_api}}</h1>
</body>
</html>