PROJECT/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView
from organization.views import DashboardView
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(DashboardView.as_view()), name='dashboard'),
	path('order/', include(('order.urls', 'order'), namespace='order')),
	path('route/', include(('route.urls', 'route'), namespace='route')),
	path('driver/', include(('driver.urls', 'driver'), namespace='driver')),
	path('vehicle/', include(('vehicle.urls', 'order'), namespace='vehicle')),
	path('accounts/', include(('user.urls', 'accounts'), namespace='accounts')),
	path('organizations/', include(('organization.urls', 'organization'), namespace='organization')),

    path('api/v1/', include('api.urls')),
    #path('', RedirectView.as_view(url=reverse_lazy('organizations:index')), name='home'),
]

api/order/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
	path('', views.FilterView.as_view()),
    path('by-ref', views.RefView.as_view()),
	path('sync', views.SyncOrderView.as_view()),
	path('replicate', views.ReplicateOrderView.as_view()),

	path('create', views.CreateView.as_view()),
    path('<int:pk>', views.IndexView.as_view()),
    path('<int:pk>/cancel', views.CancelView.as_view()),
]

api/urls.py
from django.urls import path, include

urlpatterns = [
    path("user/", include("api.user.urls")),
    path("order/", include("api.order.urls")),
    # Uses custom token
    path("driver/", include("api.driver.urls")),
    path("appointments/", include("api.appointments.urls")),
    # path("organizations/", include("api.organizations.urls")),
]

order/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

urlpatterns = [
    path('track/<str:public_id>', views.ReviewView.as_view(), name='track'),
    path('review/<str:public_id>', views.ReviewView.as_view(), name='review'),

    path('', login_required(views.IndexView.as_view()), name='index'),
    path('map', login_required(views.MapView.as_view()), name='map'),
    path('plan', login_required(views.PlanView.as_view()), name='plan'),
    path('json', login_required(views.OrdersJsonView.as_view()), name='json'),
    path('create', login_required(views.CreateView.as_view()), name='create'),
    path('<int:pk>', login_required(views.OrderView.as_view()), name='detail'),
    path('reviews', login_required(views.ReviewsView.as_view()), name='reviews'),
    path('export', login_required(views.ExportOrdersView.as_view()), name='export'),
    path('payments', login_required(views.PaymentsView.as_view()), name='payments'),
    path('track', login_required(views.OrderTrackingIframeView.as_view()), name='track'),
    path('route/json', login_required(views.RouteJsonView.as_view()), name='route-json'),
    path('<int:pk>/partial', login_required(views.OrderPartialView.as_view()), name='detail-partial'),
    path('export/reviews', login_required(views.ExportReviewsView.as_view()), name='export-reviews'),
    path('upload/iframe', login_required(views.UploadOrdersIframeView.as_view()), name='upload-iframe'),
    path('state/<int:pk>/iframe', login_required(views.StateIframeView.as_view()), name='state-iframe'),
    path('assign/<int:pk>/iframe', login_required(views.AssignIframeView.as_view()), name='assign-iframe'),
    path('pickup/<int:pk>/iframe', login_required(views.PickupIframeView.as_view()), name='pickup-iframe'),
    path('dropoff/<int:pk>/iframe', login_required(views.DropoffIframeView.as_view()), name='dropoff-iframe'),
    path('multi-assign/iframe', login_required(views.MultiAssignIframeView.as_view()), name='multi-assign-iframe'),
    path('ajax-assign/iframe', login_required(views.AjaxAssignIframeView.as_view()), name='ajax-assign-iframe'),
    path('export/driver/reviews', login_required(views.ExportDriverReviewsView.as_view()), name='export-driver-reviews'),
    path('ajax-assign/iframe/<int:vehicle_id>/<int:route_id>', login_required(views.AjaxAssignIframeView.as_view()), name='ajax-assign-iframe'),
]

order/models.py
from django.contrib.postgres.fields import ArrayField
from django.db.models.signals import post_save
from django.db import connection, OperationalError
from organization.models import Organization
from django.dispatch import receiver
from django.utils import timezone
from driver.models import Driver, Coords
from user.models import User
from django.db import models
import datetime, validators

from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer




# from django_fsm import FSMIntegerField

# For logging
class OrderStatusLog(models.Model):
	order_id = models.ForeignKey('Order', on_delete=models.CASCADE, related_name='order_status_logs')
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now_add=True)
	action = models.CharField(max_length=50)

	class Meta:
		"""Meta definition for OrderStatusLog."""

		verbose_name = 'OrderStatusLog'
		verbose_name_plural = 'OrderStatusLogs'

	def __str__(self):
		"""Unicode representation of OrderStatusLog."""
		return f'{self.action}'


class OrderItem(models.Model):
	COLLECTED = 1
	NOT_COLLECTED = 2
	DAMAGED = 3
	REJECTED = 4
	FAILED = 5
	DELIVERED = 6
	RETURNED = 7

	STATUSES = (
		(NOT_COLLECTED,'Not collected'),
		(COLLECTED,'Collected for delivery'),
		(DAMAGED,'Damaged in transit'),
		(REJECTED,'Rejected by recipeint'),
		(FAILED,'Failed'),
		(DELIVERED,'Delivered'),
		(RETURNED, 'Returned to warehouse'),
	)
	name = models.CharField(max_length=75)
	paid = models.BooleanField(default=False)
	state = models.PositiveIntegerField(choices=STATUSES,default=NOT_COLLECTED)
	price = models.DecimalField(max_digits=50,decimal_places=2, null=True)
	width = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	weight = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	length = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	height = models.DecimalField(max_digits=12, decimal_places=2, null=True)

class OrderFailure(models.Model):
	reason = models.CharField(max_length=1024)
	created = models.DateTimeField(auto_now_add=True)

class Order(models.Model):
	#payment status
	PREPAID = 1
	POSTPAID = 2
	POSTPAID_MM = 3
	CREDIT = 4

	#Vehicle types

	TBD = 0
	MOTOBIKE = 1
	MOTOBIKEWITHBOX = 2
	PICKUP_OPEN = 3
	PICKUP_CLOSED = 4
	VAN = 5
	TRUCK_3T = 6
	TRUCK_4T = 7
	TRUCK_5T = 8
	TRUCK_7T = 9
	TRUCK_10T = 10
	TRUCK_12T = 11
	TRUCK_25T = 12
	TRUCK_27T = 13
	TRUCK_3T_REFER = 14
	TRAILER = 15
	INTER_COUNTY = 16
	GLOBAL = 17


	PAYMENT_METHOD = (
		(PREPAID,'Prepaid'),
		(POSTPAID,'Postpaid - Cash'),
		(POSTPAID_MM,'Postpaid - Mobile money'),
		(CREDIT,'Credit'),
	)

	VEHICLE_TYPES = (
		(TBD, 'TBD'),
		(MOTOBIKE, 'Motorbike'),
		(MOTOBIKEWITHBOX, 'Motorbike with box'),
		(PICKUP_OPEN, 'Pick Up Open'),
		(PICKUP_CLOSED, 'Pick Up Closed'),
		(VAN, 'Van'),
		(TRUCK_3T, 'Truck 3 Tone'),
		(TRUCK_4T, 'Truck 4 Tone'),
		(TRUCK_5T, 'Truck 5 Tone'),
		(TRUCK_7T, 'Truck 7 Tone'),
		(TRUCK_10T, 'Truck 10 Tone'),
		(TRUCK_12T, 'Truck 12 Tone'),
		(TRUCK_25T, 'Truck 25 Tone'),
		(TRUCK_27T, 'Truck 27 Tone'),
		(TRUCK_3T_REFER, 'Truck 3 Tone Refer'),
		(TRAILER, 'Trailer 27 Ton with container'),
		(INTER_COUNTY, 'Inter-county'),
		(GLOBAL, 'Global'),
	)


	# delivery state
	DRAFT = 1
	""" submitted time """
	SUBMITTED_PENDING_VENDOR_PICK_UP = 2
	SUBMITTED_PENDING_FOWARD_DELIVERY = 3
	""" Dispatched """
	DISPATCHED = 4
	""" Arrival at client """
	ARRAVAL_AT_CLIENT = 5
	""" Failed """
	FAILED_AT_CLIENT = 6
	""" delivered """
	DELIVERED = 7
	""" submit to warehouse """
	SUBMITTED_RETURN_TO_WAREHOUSE = 8
	""" complete """
	COMPLETED_TO_WAREHOUSE = 9
	""" vendor """
	SUBMITTED_RETURN_TO_VENDOR = 10
	""" complete to vendor  """
	COMPLETED_TO_VENDOR = 11
	""" Admin approve all completed orders """
	CANCELLED = 12
	""" Admin approve all completed orders """
	RESCHEDULED = 13
	""" Order has been rescheduled """

	DELIVERY_STATE = (
		(DRAFT,'Submitted'),
		(SUBMITTED_PENDING_VENDOR_PICK_UP,'Driver Unassigned'),
		(SUBMITTED_PENDING_FOWARD_DELIVERY,'Driver Assigned'),
		(DISPATCHED,'in progress'),
		(ARRAVAL_AT_CLIENT, 'Arrival at client'),
		(FAILED_AT_CLIENT, 'Failed'),
		(DELIVERED, 'Delivered'),
		(SUBMITTED_RETURN_TO_WAREHOUSE, 'failed awaiting warehouse'),
		(COMPLETED_TO_WAREHOUSE, 'Delivered at warehouse'),
		(SUBMITTED_RETURN_TO_VENDOR, 'Returned from warehouse'),
		(COMPLETED_TO_VENDOR, 'Recieved from warehouse'),
		(CANCELLED, 'Cancelled'),
		(RESCHEDULED, 'Rescheduled'),

	)

	ANYTIME = 1
	MORNING = 2
	AFTERNOON = 3

	PREFERED_TIME = (
		(ANYTIME, 'Anytime'),
		(MORNING, 'Morning'),
		(AFTERNOON, 'Afternoon')
	)
	paid = models.BooleanField(default=False)
	notes = models.TextField(blank=True, null=True)
	ref = models.CharField(max_length=50, null=True)
	sid = models.CharField(max_length=50, null=True, blank=True)
	public_id = models.CharField(max_length=75, null=True, unique=True)
	state = models.PositiveIntegerField(choices=DELIVERY_STATE,default=DRAFT)
	# Bump state to status
	# status = FSMIntegerField(default=DRAFT)
	payment_method = models.PositiveSmallIntegerField(choices=PAYMENT_METHOD,default=PREPAID)


	modified = models.DateTimeField(auto_now=True)
	created = models.DateTimeField(auto_now_add=True)


	datetime_failed = models.DateTimeField(null=True)
	datetime_started = models.DateTimeField(null=True)
	datetime_arrived = models.DateTimeField(null=True)
	datetime_assigned = models.DateTimeField(null=True)
	datetime_accepted = models.DateTimeField(null=True)
	datetime_reviewed = models.DateTimeField(null=True)
	datetime_completed = models.DateTimeField(null=True)
	datetime_ordered = models.DateTimeField(default=timezone.now)

	failure_reason = models.CharField(max_length=255, null=True)
	complete_lat = models.DecimalField(max_digits=22, decimal_places=16, null=True)
	complete_lng = models.DecimalField(max_digits=22, decimal_places=16, null=True)

	payment_notes = models.CharField(max_length=2048, null=True)
	signature = models.URLField(max_length=2048, null=True)
	pod_images = ArrayField(models.URLField(max_length=2048), null=True)

	price = models.DecimalField(max_digits=50,decimal_places=2, null=True)
	width = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	weight = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	length = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	height = models.DecimalField(max_digits=12, decimal_places=2, null=True)

	pickup_location_details = models.TextField(null=True)
	pickup_location_name = models.CharField(max_length=255)
	pickup_contact_phone_number = models.BigIntegerField(null=True)
	pickup_contact_name = models.CharField(max_length=255, null=True)
	pickup_contact_email = models.EmailField(max_length=254, null=True)
	pickup_location_name_more = models.CharField(max_length=255, null=True)
	pickup_lat = models.DecimalField(max_digits=22, decimal_places=16, null=True)
	pickup_lng = models.DecimalField(max_digits=22, decimal_places=16, null=True)

	dropoff_location_details = models.TextField(null=True)
	dropoff_location_name = models.CharField(max_length=255)
	dropoff_contact_phone_number = models.BigIntegerField(null=True)
	dropoff_contact_name = models.CharField(max_length=255, null=True)
	dropoff_contact_email = models.EmailField(max_length=254, null=True)
	dropoff_location_name_more = models.CharField(max_length=255, null=True)
	dropoff_lat = models.DecimalField(max_digits=22, decimal_places=16, null=True)
	dropoff_lng = models.DecimalField(max_digits=22, decimal_places=16, null=True)

	customer_phone_number = models.BigIntegerField(null=True)
	customer_email = models.EmailField(max_length=254, null=True)
	customer_last_name = models.CharField(max_length=75, null=True)
	customer_first_name = models.CharField(max_length=75, null=True)

	review = models.CharField(max_length=2048, null=True, blank=True)
	rating = models.DecimalField(max_digits=2, decimal_places=1, null=True)

	rider = models.ForeignKey(Driver, on_delete=models.SET_NULL, null=True)
	vehicle_type = models.PositiveSmallIntegerField(choices=VEHICLE_TYPES, default=TBD)

	preffered_delivery_date = models.DateField(default=datetime.date.today)
	preffered_delivery_period = models.PositiveSmallIntegerField(default=ANYTIME, choices=PREFERED_TIME)

	failures = models.ManyToManyField(OrderFailure)
	organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
	added_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name="order_added_by")
	modified_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name="order_modified_by")

	items = models.ManyToManyField(OrderItem)

	prev_id = models.BigIntegerField(null=True, db_index=True)
	prev_id_external = models.BigIntegerField(null=True, db_index=True)

	class Meta:
		unique_together = [['ref', 'organization']]
		index_together = [
			["rider", "datetime_ordered", "state", "organization"],
			["datetime_ordered", "state", "organization"],
			["rating", "datetime_ordered", "organization"],
		]

	def mpesa_code(self):


			# check if mpesa transaction exists
		mpesa_exists = MpesaPayments.objects.filter(order__pk =self.pk).exists()

		if mpesa_exists:
			details = MpesaPayments.objects.filter(order__pk =self.pk)
			return details
		else:
			return None

	def driver_location(self):
		if self.rider is not None and self.rider.get_driver_location() is not None:
			return self.rider.get_driver_location()

		if validators.truthy(self.pickup_lat) and \
			validators.truthy(self.pickup_lng) and \
			validators.between(self.pickup_lng, -180.0, 180.0) and \
			validators.between(self.pickup_lat, -90.0, 90.0):
			c = Coords()
			c.lat = self.pickup_lat
			c.lng = self.pickup_lng
			return c

		return None


	def time_ago(self):
		d = timezone.now() - self.created
		return self.hms(d.total_seconds())

	def driver_time_ago(self):
		if self.datetime_assigned:
			d = timezone.now() - self.datetime_assigned
			return self.hms(d.total_seconds())
		else:

templates/order/create-old.html
{% extends "base.html" %}{% load static %}
{% block title %} Drivers {% endblock %}
{% block styles %} 

	<link rel="stylesheet" href="{% static "theme/css/jquery.datetimepicker.min.css" %}">
{% endblock %}

{% block content %}
<div>			
	<!-- Dashboard Headline -->
	<div class="dashboard-headline">
		<h3>Create a new order</h3>
	</div>

	<!-- Row -->
	<div class="row">
		<div class="col-xl-12">
			<div class="dashboard-box margin-top-0">

				<!-- Headline -->
				<div class="headline">
					<h3><i class="icon-feather-folder-plus"></i> Order creation form</h3>
				</div>

				<div class="content with-padding padding-bottom-10">

					<div class="row">
						<div class="col-xl-12">
						{% for field in form %}
						  {% if field.errors %}
							{% for error in field.errors %}
							<div class="alert alert-danger alert-dismissible fade show" role="alert">
							  {{ error }}
							  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
							</div>
							{% endfor %}
						  {% endif %}
						{% endfor %}	
						</div>
					</div>

					<div class="row">
						<div class="col-xl-12">
							<div class="submit-field">
								<h5>Customer details</h5>
								<div class="row">
									<div class="col-xl-3">
										<div class="submit-field">
											<h6>Name <span>(optional)</span></h6>
											<input type="text" id="customer_name" class="with-border">
										</div>
									</div>
									<div class="col-xl-3">
										<div class="submit-field">
											<h6>Phone number <span>(optional)</span></h6>
											<input type="number" id="customer_phone_number" class="with-border">
										</div>
									</div>
									<div class="col-xl-3">
										<div class="submit-field">
											<h6>Email <span>(optional)</span></h6>
											<input type="email"  id="customer_email"  class="with-border">
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>


					<div class="row">
						<div class="col-xl-12">
							<div class="submit-field">
								<h5>Order details</h5>
								<div class="row">
									<div class="col-xl-3">
										<div class="submit-field">
											<h6>Ref: <span>(optional)</span></h6>
											<input type="text"  id="order_ref" class="with-border">
										</div>
									</div>

									<div class="col-xl-3">
										<div class="submit-field">
											<h6>Delivery date & time  <span>(optional)</span></i></h6>
											<div class="input-with-icon">
												<div id="autocomplete-container">
													<input class="with-border" type="text" autocomplete="off" readonly id="delivery_date">
												</div>
												<i class="icon-material-outline-date-range"></i>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>

						<div class="col-xl-12">
							<div class="row">

								<div class="col-xl-2">
									<div class="submit-field">
										<h6>Length <span>(optional)</span></h6>
										<div class="input-with-icon">
											<input class="with-border" id="length" type="number" min=1>
											<i class="currency">cms</i>
										</div>
									</div>
								</div>
								<div class="col-xl-2">
									<div class="submit-field">
										<h6>Width <span>(optional)</span></h6>
										<div class="input-with-icon">
											<input class="with-border" id="width" type="number" min=1>
											<i class="currency">cms</i>
										</div>
									</div>
								</div>
								<div class="col-xl-2">
									<div class="submit-field">
										<h6>Height <span>(optional)</span></h6>
										<div class="input-with-icon">
											<input class="with-border" id="height" type="number" min=1>
											<i class="currency">cms</i>
										</div>
									</div>
								</div>
								<div class="col-xl-2">
									<div class="submit-field">
										<h6>Weight <span>(optional)</span></h6>
										<div class="input-with-icon">
											<input class="with-border" id="weight" type="number" min=1>
											<i class="currency">kgs</i>
										</div>
									</div>
								</div>


								<div class="col-xl-2">
									<div class="submit-field">
										<h6>Price <span>(optional)</span></h6>
										<div class="input-with-icon">
											<input class="with-border" id="price" type="number" min=1>
											<i class="currency">ksh</i>
										</div>
									</div>
								</div>

								<div class="col-xl-2">
									<div class="submit-field">
										<h6>Payment method</h6>
										<div class="btn-group bootstrap-select with-border">
											<select class="selectpicker with-border" data-size="7" title="Delivery period" tabindex="-98"><option class="bs-title-option" value="">Select a payment method</option>
												<option selected>Prepaid</option>
												<option>Postpaid</option>
												<option>Credit</option>
											</select>
										</div>
									</div>
								</div>

							</div>
						</div>

					</div>


					<div class="row">

							<div class="col-xl-6">
								<div class="row">
									<div class="col-xl-12">

										<div class="submit-field">
											<h5>Pickup contact details</h5>
											<div class="row">
												<div class="col-xl-7">
													<h6>Address</h6>
													<div class="input-with-icon">
														<div id="autocomplete-container">
															<input id="pickup-location" class="with-border" id="pickup_address" type="text" autocompete="off">
														</div>
														<i class="icon-material-outline-location-on"></i>
													</div>
												</div>
												<div class="col-xl-5">
													<h6>Road/Apartment/Hse. No</h6>
													<div class="submit-field">
														<input type="text" class="with-border" id="pickup_more">
													</div>
												</div>
											</div>
											<div class="row">
												<div class="col-xl-4">
													<h6>Name</h6>
													<div class="submit-field">
														<input type="text" class="with-border" id="pickup_name">
													</div>
												</div>
												<div class="col-xl-4">
													<h6>Phone number</h6>
													<div class="submit-field">
														<input type="number" class="with-border" id="pickup_phone_number">
													</div>
												</div>
												<div class="col-xl-4">
													<h6>Email</h6>
													<div class="submit-field">
														<input type="email" class="with-border" id="pickup_email">
													</div>
												</div>
											</div>
										</div>
									

									</div>
								</div>
							</div>

							<div class="col-xl-6">
								<div class="row">
									<div class="col-xl-12">
									
										<div class="submit-field">
											<h5>Drop-off contact details</h5>
											<div class="row">
												<div class="col-xl-7">
													<h6>Address</h6>
													<div class="input-with-icon">
														<div id="autocomplete-container">
															<input id="pickup-location" class="with-border" type="text" id="dropoff_address" autocompete="off">
														</div>
														<i class="icon-material-outline-location-on"></i>
													</div>
												</div>
												<div class="col-xl-5">
													<h6>Road/Apartment/Hse. No</h6>
													<div class="submit-field">
														<input type="text" class="with-border" id="dropoff_more">
													</div>
												</div>
											</div>
											<div class="row">
												<div class="col-xl-4">
													<h6>Name</h6>
													<div class="submit-field">
														<input type="text" class="with-border" id="dropoff_name" >
													</div>
												</div>
												<div class="col-xl-4">
													<h6>Phone number</h6>
													<div class="submit-field">
														<input type="number" class="with-border" id="dropoff_phone_number" >
													</div>
												</div>
												<div class="col-xl-4">
													<h6>Email</h6>
													<div class="submit-field">
														<input type="email" class="with-border" id="dropoff_email">
													</div>
												</div>
											</div>
										</div>

									</div>
								</div>
							</div>

					</div>




					<div class="row">
						<div class="col-xl-12">
							<div class="submit-field">
								<h5>Notes <span>(optional)</span></h5>
								<textarea cols="30" rows="5" class="with-border"></textarea>
							</div>
						</div>
					</div>

				</div>

			</div>
		</div>

		<div class="col-xl-12">
			<button class="button ripple-effect big margin-top-30" form="submit-form" id="submit-form"><i class="icon-feather-plus"></i> Create order</button>
		</div>
	</div>
	<!-- Row / End -->

</div>
<form action="" method="post" style="display:none" id="form-hidden">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% endblock content %}
{% block scripts %}
<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
<script src="https://maps.googleapis.com/maps/api/js?key={% if map_api %}{{map_api}}{% else %}AIzaSyDrEYEy6nXlouW4TCD_r3sGs44MwHAS3z4{% endif %}&callback=initMap&libraries=places&v=weekly" defer></script>
<script src="{% static "theme/js/jquery.datetimepicker.full.min.js" %}"></script>

<script>
  $(document).ready(function() {
	$('#customer_name').val($("#id_customer_name").val());
	$('#customer_email').val($("#id_customer_email").val());
	$('#customer_phone_number').val($("#id_customer_phone_number").val());

	$('#order_ref').val($("#id_ref").val());

	$('#length').val($("#id_length").val());
	$('#width').val($("#id_width").val());
	$('#height').val($("#id_height").val());
	$('#weight').val($("#id_weight").val());
	$('#price').val($("#id_price").val());


	
     $("#submit-form").click(function(event) {
        event.preventDefault();
		$('#id_customer_name').val($("#customer_name").val());
		$('#id_customer_email').val($("#customer_email").val());
		$('#id_customer_phone_number').val($("#customer_phone_number").val());

		$('#id_ref').val($("#order_ref").val());

		$('#id_length').val($("#length").val());
		$('#id_width').val($("#width").val());
		$('#id_height').val($("#height").val());
		$('#id_weight').val($("#weight").val());
		$('#id_price').val($("#price").val());

		$('#form-hidden').submit();
     });
  });

  // This example requires the Places library. Include the libraries=places
  // parameter when you first load the API. For example:
  // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">
  function initMap() {
    const input_pickup = document.getElementById("pickup-location");
    const input_dropoff = document.getElementById("dropoff-location");
    const autocomplete_pickup = new google.maps.places.Autocomplete(input_pickup);
    const autocomplete_dropoff = new google.maps.places.Autocomplete(input_dropoff);
    // Set the data fields to return when the user selects a place.
    autocomplete_pickup.setFields([
      "address_components",
      "geometry",
      "icon",
      "name",
    ]);
    autocomplete_dropoff.setFields([
      "address_components",
      "geometry",
      "icon",
      "name",
    ]);
  }
  $(function () {
	$("#delivery_date").datetimepicker({
	  minDate:0,
	  minTime:new Date(),
	  format: 'm/d/Y h:m',
	});
  });
</script>
{% endblock scripts %}

templates/order/dropoff_iframe.html
{% extends "base_iframe.html" %}{% load static %}
{% block title %} Dropoff {% endblock %}


{% block content %}
<div>			
	<!-- Dashboard Headline -->
	<div class="welcome-text">
		<h3>Dropoff details</h3>
	</div>
	<!-- Row -->
	<div class="row">
		<div class="col-xl-12">
			<!--Tabs -->
			<div class="sign-in-form">

				<ul class="popup-tabs-nav">
				</ul>

				<div class="popup-tabs-container">

					<!-- Tab -->
					<div class="popup-tab-content" id="tab2">
					
						<div class="job-listing-footer">
							<ul class="dashboard-box-list">
								<li><i class="icon-feather-user"></i>&nbsp;&nbsp;
									{% if object.dropoff_contact_name %}
										<h4 class="capitalize">{{object.dropoff_contact_name  | lower }}</h4>
									{% endif %}
								</li>
							</ul>
							<ul class="dashboard-box-list">
								<li><i class="icon-feather-phone"></i>&nbsp;&nbsp; 
									{% if object.dropoff_contact_phone_number %}
										<span class="capitalize"><a href="tel:+{{object.dropoff_contact_phone_number}}">+{{object.dropoff_contact_phone_number}}</a></span>
									{% endif %}
								</li>
							</ul>
							<ul class="dashboard-box-list">
								<li><i class="icon-material-outline-location-on"></i>&nbsp;&nbsp; {{object.dropoff_location_name}}</li>
							</ul>

						</div>

					</div>

				</div>
			</div>


		</div>
	</div>
	<!-- Row / End -->

</div>
{% endblock content %}